### ISSUE TITLE
Test starchat

### ISSUE THREAD

**Issue by deepiksdev** [deepiksdev/starchat#1]
@ALLENWAN1 @petetiR I believe this could be an interesting solution to complete our platform. Can one of you test ? FYI, I have posted an issue at https://github.com/GetJenny/starchat/issues/64

**Comment by ALLENWAN1** [comment]
@deepiksdev I tried to test starchat, but when I load the configuration file by running this command:
```sbt "run-main com.getjenny.command.IndexDecisionTable --inputfile doc/sample_state_machine_specification.csv --skiplines 1"```

I got a error:
``` 
[error] (run-main-0) akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]]
akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]]
	at akka.event.LoggingBus.startDefaultLoggers(Logging.scala:146)
	at akka.event.LoggingBus.startDefaultLoggers$(Logging.scala:98)
	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:23)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:652)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:796)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:793)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:793)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:809)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:244)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:287)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:232)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:223)
	at com.getjenny.command.IndexDecisionTable$.doIndexDecisionTable(IndexDecisionTable.scala:42)
	at com.getjenny.command.IndexDecisionTable$.main(IndexDecisionTable.scala:147)
	at com.getjenny.command.IndexDecisionTable.main(IndexDecisionTable.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
[error] (compile:runMain) Nonzero exit code: 1
[error] Total time: 9 s, completed Jun 27, 2017 4:28:56 PM
```

**Comment by deepiksdev** [comment]
@ALLENWAN1 @petetiR I understand that you both tested using 2 different environments (Ubuntu and Pc), and both got the same error. Please confirm, and if so, please post an issue on the publisher's repository.

**Comment by petetiR** [comment]
@deepiksdev 
Actualy, it's indeed at the same step, but not exactly the same error. 
I continue trying since I'm not sure to do it the right way.

**Comment by ALLENWAN1** [comment]
@deepiksdev @petetiR I use my ubuntu, and the error of sbt is disappeared, but I got a new error.

When I send a request as follow:
```
curl -v -H "Content-Type: application/json" -X POST http://localhost:8888/index_management/create"
```

I got 

```
HTTP/1.1 400 Bad Request
< application: json
< Server: akka-http/10.0.7
< Date: Thu, 29 Jun 2017 14:03:19 GMT
< Content-Type: application/json
< Content-Length: 129
< 
* Connection #0 to host localhost left intact
{"message":"None of the configured nodes are available:

```

**Comment by ALLENWAN1** [comment]
@deepiksdev @petetiR 
It's unbelievable. I backed to use my macbook. Now, it works well and all command passed.
I successfully tested the document.

sent request by: 
```
curl  -H "Conte/json" -X POST http://localhost:8888/get_next_response -d '{
>  "conversation_id": "1234",
>   "user_input": { "text": "Please send me the test state" },
>   "values": {
>       "return_value": "",
>       "data": {}
>        }
>   }'
```

And got 
```
[{"analyzer":"booleanAnd(booleanNot(booleanOr(keyword(\"dont\"),keyword(\"don't\"))), keyword(\"test\"), booleanOr(keyword(\"send\"), keyword(\"get\")))","state":"test_state","data":{},"state_data":{},"score":1.0,"success_value":"","failure_value":"","bubble":"This is the test state","action_input":{},"max_state_count":0,"conversation_id":"1234","action":""}]
```

**Comment by deepiksdev** [comment]
@ALLENWAN1 

> I successfully tested the document.

Congrats. What document did you test ? Can you test with : https://github.com/GetJenny/starchat/blob/master/doc/sample_state_machine_specification.csv ?

**Comment by ALLENWAN1** [comment]
@deepiksdev 
> What document did you test

yes. I tried to figure out how to add some exemples.

**Comment by petetiR** [comment]
@deepiksdev  
For my part, I'm struggling with this command (which for some reason was working well Wednesday) : 
```
docker-compose up -d
```
I got : 
```
ERROR: for starchat  Cannot start service starchat: containerd: container not started
```
I tried ```docker build .``` to maybe build those missing containers, but without success.
I also tried to build starchat and elasticsearch separately, but again, no success.

**Comment by deepiksdev** [comment]
Our tests have not been successful , let's close this issue now.

**Comment by angleto** [comment]
@ALLENWAN1 about the command:

```bash
sbt "run-main com.getjenny.command.IndexDecisionTable --inputfile doc/sample_state_machine_specification.csv --skiplines 1"
```

The issue could be due to the command which tries to write logs into a starchat/logs folder. If the folder is already created with root ownership or if the command cannot create the folder it rises this error.
The above is the only way I was able to reproduce the problem.

**Comment by angleto** [comment]
@ALLENWAN1  about the command:

```bash
curl -v -H "Content-Type: application/json" -X POST http://localhost:8888/index_management/create"
```

The problem could be due to elasticsearch which has not yet started after the docker-compose up command.

**Comment by angleto** [comment]
@petetiR 
the message:

```bash
ERROR: for starchat  Cannot start service starchat: containerd: container not started
```

may happen when the docker daemon is down or it has some throuble

**Comment by ALLENWAN1** [comment]
@angleto Thanks a lot. I will try to solve it according to your comments. And in fact, we have a machine which have successfully installed starchat, so we will test it later. Thanks again for your helps.

**Comment by angleto** [comment]
@deepiksdev @ALLENWAN1 

there's another sample spreadsheet: doc/decision_table_starchat_doc.csv which contains a draft for a chatbot with the documentation for StarChat.

If could be useful to you for testing, there is also a basic nodejs web application for starchat: https://github.com/GetJenny/starchat-demo
